### PR TITLE
Implemented geocode API functionality

### PR DESCRIPTION
**Pull request by PolBaladas**

### CODE REVIEW

**Comment by sudheesh001** [comment]
@PolBaladas Can you also include the way to use this in the `sample.py` functions.

**Comment by PolBaladas** [comment]
Done! I've added samples for single places and multiple places.

**Comment by sudheesh001** [comment]
@PolBaladas Good work !

**Comment by PolBaladas** [comment]
Thanks!

**Comment by PolBaladas** [comment]
Can I implement this one too? http://loklak.org/api.html#map 
I guess that would mean to reopen the task so i can do it twice or something like that...?

**Comment by sudheesh001** [comment]
@PolBaladas There's a parental consent pending. I think once its approved you'd be allowed to pick it again. Or i'll reopen it so that you can work on it. In case we open a new one, would you like me to directly assign it to you ?

**Comment by PolBaladas** [comment]
Well, I've just claimed learning REST and JSON but once I've finished that one, sure!
Is the documentation in http://loklak.org/api.html#map complete? If it is I don't understand the parameters or its use.
Thanks!

**Comment by sudheesh001** [comment]
@PolBaladas Ah I just realized that its not complete as it's supposed to be, I'll just add the required documentation to the server. In the meantime here is a sample URL
http://loklak.org/vis/map.png?text=Hello&mlat=17.582729&mlon=79.118320&zoom=12&width=512&height=512

**Comment by PolBaladas** [comment]
Nice! now it's easier hehe
Thanks

**Comment by PolBaladas** [comment]
Hi sudheesh, yes please, if you open a new task regarding the map API implementation i would like to work on it. Thanks! (I've submitted for review the other task so i'll be available soon) :+1:  :)

**Comment by sudheesh001** [comment]
Great. Will let you know once reopened or a new instance created.

**Comment by PolBaladas** [comment]
Cool! Thanks!

**Comment by PolBaladas** [comment]
I've finished the other task. I'm available!

**Comment by PolBaladas** [comment]
Hi, will you reopen the task soon? I'm asking for if i can claim another task or wait for this one.
Thanks.

**Comment by sudheesh001** [comment]
@PolBaladas Please continue with other tasks, It doesn't look like we'd be reopening it anytime soon. :+1:

**Comment by PolBaladas** [comment]
Ok! No problem, Thanks

**Pull request merged**
