### PR TITLE
Implemented count parameter in the search function

### PR DESCRIPTION
**Pull request by gunvirranu**
I didn't know what else to implement at the moment. Now there is a `count` parameter that specifies  how many tweets you want returned. Also added a test in sample.py and added documentation in the README. I don't know if this is useful, but take a look anyway. Thanks.

Btw, this is not a GCI task. Just interested in the project.

### CODE REVIEW

**Comment by sudheesh001** [comment]
Please squash into a single commit ! Good work @gunvirranu Also update the documentation in README for the `search()`

**Comment by gunvirranu** [comment]
I already updated the documentation in the README.
How do you squash them into a single commit?

**Comment by gunvirranu** [comment]
Could you just close this actually. I'd rather just do it again cause I accidentally messed up the commits in my fork trying to squash them. Unless you could help me fix this?

**Comment by sudheesh001** [comment]
I hope this will solve the issue. https://asciinema.org/a/11269

**Comment by sudheesh001** [comment]
Also don't forget after rebasing, you need to do a force push or it'll complain about pull before push. so add , `-f` at the end of your `git push ..... ` statement

**Comment by gunvirranu** [comment]
Thanks. But I'm going to open another PR as I messed up my current fork by trying to squash the commits.

**Comment by sudheesh001** [comment]
Tip: Always contribute using branches, never master !

**Comment by gunvirranu** [comment]
Thanks for the tip. I did use a branch, but I merged the branch with master and couldn't figure out how to squash the commits. That eventually led to a bunch of things messing up.
I made a new PR if you didn't see btw.

**Pull request closed without merging**
