### PR TITLE
Integrate Travis, refactor unit test, add unit test for geocode module

### PR DESCRIPTION
**Pull request by sevazhidkov**
https://codein.withgoogle.com/dashboard/task-instances/6497229124665344/

### CODE REVIEW

**Comment by sudheesh001** [comment]
@sevazhidkov Good work, Please rebase all commits into one single commit.

**Comment by sevazhidkov** [comment]
Something went wrong. How can I delete not mine commits?

**Comment by sudheesh001** [comment]
Do the following
```
git reset --hard cf54537e0486291d4356bf65e42430aa023274ac
git pull https://github.com/loklak/python-loklak-api/ master
```
This would mean the commits you've made will be gone and you'd have to redo them, So you can have a look at your commits
1. https://github.com/sevazhidkov/python-loklak-api/commit/266c1a4ca62045827e706bea5b16f2c5ecc8b50e
2. https://github.com/sevazhidkov/python-loklak-api/commit/4ac63340a0cba450fa9f552d892be30f20160550
3. https://github.com/sevazhidkov/python-loklak-api/commit/49085146076d88aecce0200e22d505d5ef81aab2
4. https://github.com/sevazhidkov/python-loklak-api/commit/22f4f4ab2d6860a2b63a49c56d69170e590c7ffa
5. https://github.com/sevazhidkov/python-loklak-api/commit/7e187fb8beeef1174751cec8d0ced73714ab4c53

And combine the changes made in all these into the code base again and send a forced update to master.

**Comment by sudheesh001** [comment]
@sevazhidkov There are 9 commits now to fix one problem, This isn't recommended. Please rebase and squash the commits. Maybe this video will be of help.

https://asciinema.org/a/11269

**Comment by sevazhidkov** [comment]
I already rebased my commits, but some commits from other people that made before mine shown in this pull request.

**Comment by sevazhidkov** [comment]
I will create new pull request.

**Pull request closed without merging**
