### PR TITLE
Fix code style to PEP8

### PR DESCRIPTION
**Pull request by sevazhidkov**

### CODE REVIEW

**Comment by sudheesh001** [comment]
@sevazhidkov Which IDE are you using ? Why did you change the default 4 spacing to 8 and change it back to 4 ? I don't think i'll let this pass at the moment. Thanks for the work though.

**Comment by sevazhidkov** [comment]
Right now loklak.py is with 8 spacing. I fix it using autopep8 module.

**Comment by sudheesh001** [comment]
Ah, I am not in an IDE, hence the code is running with a 4 spacing method. Please ignore this problem.

**Comment by sevazhidkov** [comment]
Sorry, but it's very uncomfortable to work with it. For example, Atom editor shows code not right:


Let's use standards.

**Comment by sevazhidkov** [comment]
Also the current code style is not compatible with Python 3.

**Pull request closed without merging**
